spring:
  profiles:
    active: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
  expirationTime: 60

app-setup:
  alreadySetup: false
  adminUsername: admin
  adminPassword: admin
  adminEmail: example@gmail.com

app:
  base:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    frontend: https://cms.laklu.com
    url: https://api.laklu.com
    attachment-endpoint: /api/v1/attachments
    attendance-checkin: ${app.base.frontend}/schedule/checkin
    attendance-checkout: ${app.base.frontend}/schedule/checkout
    attendance-expire-time: 60000

web:
  cors:
    allowed-origins: "http://localhost:3015"
#sss